baseURL = "https://eventhorizon-mtg.github.io/"
languageCode = "it-it"
title = "EventHorizon.mtg"

publishDir = "public"
canonifyURLs = false
enableRobotsTXT = true

[pagination]
  pagerSize = 12

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  article = "/articles/:slug/"

[params]
  siteName = "EventHorizon.mtg"
  appVer = "63ab118"

  # Open Graph (fallback globali; sovrascrivibili per pagina con front matter)
  [params.og]
    title = "EventHorizon.mtg"
    description = "Magic: The Gathering • Video e risorse selezionate."
    image = "images/bg_image.webp"
    locale = "it_IT"

  # UI
  themeColor = "#0E0F1A"

  # Preload hero LCP (opzionale: lascia o cambia path)
  preloadHero = "images/bg_image.webp"

  # Fonts (self-hosted) preload list (WOFF2)
[params.fonts]
  preload = [
    "fonts/LexendDeca-Regular.woff2",
    "fonts/LexendGiga-Regular.woff2",
    "fonts/Merriweather-Light.woff2",
    "fonts/Roboto-Regular.woff2",
    "fonts/Roboto-Italic.woff2"
  ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats.ArchiveList]
mediaType    = "application/json"
baseName     = "list"
isPlainText  = true
notAlternative = true
permalinkable  = true


relativeURLs = true




