baseURL = "https://eventhorizonmtg.netlify.app/"
languageCode = "it-it"
title = "EventHorizon.mtg"

# Facoltativo ma utile subito
paginate = 12
enableRobotsTXT = true

# In futuro useremo le tassonomie per tag/categorie
[taxonomies]
  tag = "tags"
  category = "categories"
