baseURL = "https://eventhorizon-mtg.github.io/eventhorizon/"
languageCode = "it-it"
title = "EventHorizon.mtg"

publishDir = "docs"
canonifyURLs = false
enableRobotsTXT = true

[pagination]
  pagerSize = 12

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  article = "/articles/:slug/"

[params]
  siteName = "EventHorizon.mtg"
  appVer = "2025.09.27"

  # Open Graph (fallback globali; sovrascrivibili per pagina con front matter)
  [params.og]
    title = "EventHorizon.mtg"
    description = "Magic: The Gathering • Guide, video e risorse selezionate."
    image = "/images/bg_image.webp"
    locale = "it_IT"

  # UI
  themeColor = "#0E0F1A"

  # Preload hero LCP (opzionale: lascia o cambia path)
  preloadHero = "images/bg_image.webp"

[outputFormats.ArchiveList]
mediaType    = "application/json"
baseName     = "list"
isPlainText  = true
notAlternative = true
permalinkable  = true


relativeURLs = true




