baseURL = "https://eventhorizonmtg.netlify.app/"
languageCode = "it-it"
title = "EventHorizon.mtg"

enableRobotsTXT = true

[pagination]
  pagerSize = 12

[taxonomies]
  tag = "tags"
  category = "categories"
