name: Nuovo Item Archivio
description: Crea un nuovo elemento per l'Archivio (video/contenuto/portal)
labels:
  - ingest:item
body:
  - type: input
    id: id
    attributes:
      label: ID univoco (es. eh-0003)
      description: Usa un identificativo breve e unico (es. eh-0003)
      placeholder: eh-0003
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Data (YYYY-MM-DD)
      placeholder: 2025-09-27
    validations:
      required: true
  - type: dropdown
    id: kind
    attributes:
      label: Tipo
      options:
        - content
        - video
        - portal
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Titolo
    validations:
      required: true
  - type: input
    id: overline
    attributes:
      label: Overline (riga sopra il titolo)
  - type: textarea
    id: desc
    attributes:
      label: Descrizione breve
  - type: input
    id: thumb
    attributes:
      label: Thumbnail (URL assoluto o path sotto images/...)
      placeholder: images/cards/fblthp_placeholder.webp
  - type: input
    id: tags
    attributes:
      label: Tag (separati da virgola)
      placeholder: commander, lore, tutorial
  - type: input
    id: slug
    attributes:
      label: Slug pagina interna (opzionale, per articoli interni)
      placeholder: guida-commander
  - type: markdown
    attributes:
      value: "### Link principali (fino a 3)"
  - type: input
    id: link1_label
    attributes:
      label: Link 1 - Label
  - type: input
    id: link1_url
    attributes:
      label: Link 1 - URL
  - type: input
    id: link1_btn
    attributes:
      label: Link 1 - Classe bottone (es. btn--yt, btn--mox, btn--archi, primary)
  - type: input
    id: link2_label
    attributes:
      label: Link 2 - Label
  - type: input
    id: link2_url
    attributes:
      label: Link 2 - URL
  - type: input
    id: link2_btn
    attributes:
      label: Link 2 - Classe bottone
  - type: input
    id: link3_label
    attributes:
      label: Link 3 - Label
  - type: input
    id: link3_url
    attributes:
      label: Link 3 - URL
  - type: input
    id: link3_btn
    attributes:
      label: Link 3 - Classe bottone
