backend:
  name: github
  repo: eventhorizon-mtg/eventhorizon-mtg.github.io
  branch: main
  base_url: https://eventhorizon-oauth.cetriolo-mtg.workers.dev
  auth_endpoint: /auth

media_folder: "static/uploads"
public_folder: "/uploads"

# publish_mode: editorial_workflow  # opzionale: bozza → review → publish

collections:
  - name: "archive_items"
    label: "Archivio — Items"
    folder: "data/archive/items"
    create: true
    format: "yaml"
    extension: "yml"
    slug: "{{slug}}"

    fields:
      - label: "Data"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
        required: true

      - label: "Titolo"
        name: "title"
        widget: "string"
        required: true

      - label: "ID"
        name: "id"
        widget: "string"
        required: false

      - label: "Slug"
        name: "slug"
        widget: "string"
        required: false
        pattern:
          - "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          - "Minuscole, numeri e trattini (kebab-case)."

      - label: "Tipo"
        name: "kind"
        widget: "select"
        options:
          - { label: "Video", value: "video" }
          - { label: "Contenuto", value: "content" }
        required: false
        default: "content"

      - label: "Overline"
        name: "overline"
        widget: "string"
        required: false

      - label: "Descrizione"
        name: "desc"
        widget: "text"
        required: false

      - label: "Thumbnail"
        name: "thumb"
        widget: "image"
        required: false
        choose_url: true

      - label: "Tag"
        name: "tags"
        widget: "list"
        required: false
        field: { label: "Tag", name: "tag", widget: "string" }

      - label: "Link"
        name: "links"
        widget: "list"
        required: false
        fields:
          - { label: "Label", name: "label", widget: "string", required: false }
          - label: "URL"
            name: "href"
            widget: "string"
            required: false
            pattern:
              - "^https?://.*"
              - "Inserisci un URL assoluto (http/https)."
          - { label: "Classe bottone", name: "btn_class", widget: "string", required: false }
          - { label: "Ordine", name: "sort_order", widget: "number", required: false, default: 0 }
          - { label: "Primario", name: "primary", widget: "boolean", required: false, default: false }

      - { label: "Bozza", name: "draft", widget: "boolean", required: false, default: false }
      - { label: "Autore", name: "author", widget: "string", required: false }
      - { label: "Aggiornato", name: "updated", widget: "datetime", required: false }
      - { label: "Card", name: "card", widget: "string", required: false }

  # ========================================
  # ARTICOLI
  # ========================================
  - name: "articles"
    label: "📰 Articoli"
    label_singular: "Articolo"
    folder: "content/article"
    format: "frontmatter"
    extension: "md"
    create: true
    slug: "{{slug}}"
    identifier_field: title
    summary: "{{title}} - {{date}}"

    fields:
      - label: "Titolo"
        name: "title"
        widget: "string"
        required: true

      - label: "Data"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
        required: true

      - label: "Autore"
        name: "author"
        widget: "string"
        required: false

      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        allow_add: true
        default: []

      - label: "Categorie"
        name: "categories"
        widget: "list"
        required: false
        allow_add: true
        default: []

      - label: "Bozza"
        name: "draft"
        widget: "boolean"
        default: false
        required: false

      - label: "In Evidenza"
        name: "featured"
        widget: "boolean"
        default: false
        required: false

      - label: "Contenuto"
        name: "body"
        widget: "markdown"
        required: true

# Editor Settings
editor:
  preview: true

# Site Settings
locale: it
display_url: https://eventhorizon-mtg.github.io
site_url: https://eventhorizon-mtg.github.io
