backend:
  name: github
  repo: eventhorizon-mtg/eventhorizon-mtg.github.io
  branch: main
  base_url: https://eventhorizon-oauth.cetriolo-mtg.workers.dev
  auth_endpoint: /auth

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: items
    label: Archivio Items
    folder: data/archive/items
    create: true
    format: yaml
    extension: yml
    slug: "{{slug}}"
    fields:
      - label: Data
        name: date
        widget: date
        required: true
      - label: Titolo
        name: title
        widget: string
        required: true